In [31]:
import numpy as np
import matplotlib.pyplot as plt

# Creating

In [48]:
arr = np.array([1,2,3])
arr = np.array([1,5,2],dtype=np.float64)
arr = np.arange(1,5,2) 
arr = np.r_[1:13].reshape(3,4)
arr = np.linspace(1,4,13)
arr = np.random.randn(100)
arr = np.eye(4)
arr = np.zeros((3,3))
arr = np.ones(8)
arr = np.diag([1,2,3])
arr = np.full((3,4),5)
arr = np.empty((4,3))
arr = np.c_[3:7]
arr

array([[3],
       [4],
       [5],
       [6]])

# operations

In [34]:
a = np.arange(2,6)
b = np.arange(10,14)

In [35]:
a + b
a += b
a - b
np.add(a,a,a)
np.exp(a)
np.sin(a)
np.sqrt(a)
np.power(a,3)
a.dot(b)
a.argmax()

3

In [36]:
a = np.array([1,2,3,4])
b = np.array([1,3,3,5])
a == b
a[a >= b]
a[a >= b] = 200
a[(a > 2) & (a < 10)] = 55

In [37]:
a

array([200,   2, 200,  55])

In [38]:
a = np.array([1,3,2,1,2,1,2,5,6,9,2])

In [39]:
np.sum(a)
np.mean(a)
np.cumsum(a)
np.max(a)
np.corrcoef(a)
mask = np.array([0,0,1,0,1,0,0,1,0,1,1],dtype=bool)
b = a[mask]

# Manipulation

In [40]:
a = np.arange(12).reshape(3,4) # returns a new array
b = np.arange(12).reshape(3,4)*2

In [50]:
a.T
np.ravel(a)
a.resize((2,6))
np.append(a,a)
np.insert(a,1,1)
np.delete(a,1)
# np.vstack((a,b))
# np.hstack((a,b))

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])