In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Creating

In [2]:
arr1 = np.array([1,2,3])
arr1 = np.array([1,5,2],dtype=np.float64)
arr1 = np.arange(1,5,2) 
arr1 = np.r_[1:13].reshape(3,4)
arr1 = np.linspace(1,4,13)
arr1 = np.random.randn(100)
arr1 = np.eye(4)
arr1 = np.zeros((3,3))
arr1 = np.ones(8)
arr1 = np.diag([1,2,3])
arr1 = np.full((3,4),5)
arr1 = np.empty((4,3))
arr1 = np.c_[3:7]

In [3]:
arr1

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

# operations

In [3]:
a = np.arange(2,6)
b = np.arange(10,14)

In [4]:
a + b
a += b
a - b
np.add(a,a,a)
np.exp(a)
np.sin(a)
np.sqrt(a)
np.power(a,3)
a.dot(b)
a.argmax()

3

In [7]:
a = np.array([1,2,3,4])
b = np.array([1,3,3,5])
a == b
a[a >= b]
a[a >= b] = 200
a[(a > 2) & (a < 10)] = 55

In [8]:
a

array([200,   2, 200,  55])

In [98]:
a = np.array([1,3,2,1,2,1,2,5,6,9,2])

In [105]:
np.sum(a)
np.mean(a)
np.cumsum(a)
np.max(a)
np.corrcoef(a)
mask = np.array([0,0,1,0,1],dtype=bool)
b = a[mask]

1.0

# Manipulation

In [168]:
a = np.arange(12).reshape(3,4) # returns a new array
b = np.arange(12).reshape(3,4)*2

In [169]:
a.T
np.ravel(a)
a.resize((2,6))
np.append(a,a)
np.insert(a,1,1)
np.delete(a,1)
np.vstack((a,b))
np.hstack((a,b))

array([[ 0,  1,  2,  3,  0,  2,  4,  6],
       [ 4,  5,  6,  7,  8, 10, 12, 14],
       [ 8,  9, 10, 11, 16, 18, 20, 22]])